name: Run PHPUnit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  phpunit:
    name: PHPUnit Test
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: assgroup_test
          MYSQL_USER: test_user
          MYSQL_PASSWORD: test_password
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 --user=test_user --password=test_password"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2.12'
          extensions: mysqli, pdo_mysql

      - name: Install Composer Dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Import Database Schema
        run: mysql -h 127.0.0.1 -u test_user -ptest_password assgroup_test < tests/assgroup_test.sql

      - name: Set PHPUnit as Executable
        run: chmod +x vendor/bin/phpunit

      - name: Run PHPUnit Tests
        env:
          DB_HOST: 127.0.0.1
          DB_DATABASE: assgroup_test
          DB_USERNAME: test_user
          DB_PASSWORD: test_password
        run: vendor/bin/phpunit --testdox --configuration phpunit.xml --colors=always