name: CI/CD Pipeline for PHP Project

on:
  push:
    branches:
      - testing  # Trigger the pipeline on the testing branch
  pull_request:
    branches:
      - testing  # Trigger the pipeline on pull requests targeting testing

jobs:
  build:
    runs-on: ubuntu-22.04  # Use a specific Ubuntu version

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: test_db
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping --silent" --health-timeout=30s --health-retries=3

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up PHP
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, mysqli, pdo_mysql

      # Step 3: Install dependencies
      - name: Install dependencies
        run: composer install

      # Step 4: Run PHPUnit tests with execute permission
      - name: Run tests
        run: |
          chmod +x ./vendor/bin/phpunit  # Ensure phpunit has execute permission
          ./vendor/bin/phpunit tests
