name: CI/CD Pipeline for PHP Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: assgroup_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h mysql --silent"  # Use "mysql" as the host here
          --health-interval=3s
          --health-timeout=3s
          --health-retries=10
          --health-start-period=10s

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, mysqli, pdo_mysql

      - name: Verify MySQL Connection
        run: |
          for i in {1..10}; do
            if mysql -h"mysql" -P"3306" -uroot -proot -e "SELECT 1" >/dev/null 2>&1; then  # Use "mysql" as the host here
              echo "MySQL is ready!"
              exit 0
            fi
            echo "Attempt $i: Waiting for MySQL... (3s)"
            sleep 3
          done
          echo "MySQL connection failed after 10 attempts"
          exit 1

      - name: Install Dependencies
        run: composer install --prefer-dist --no-progress

      - name: Setup Database
        run: mysql -h"mysql" -P"3306" -uroot -proot assgroup_test < tests/setup_test_db.sql  # Use "mysql" as the host here

      - name: Run Tests
        run: vendor/bin/phpunit
